version: '3'
services:
  mysql:
    container_name: takeaway_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: takeaway
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
  php:
    container_name: takeaway_php
    build: ./docker/php
    volumes:
      - .:/www

  rabbitmq:
    container_name: takeaway_rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
      - "5672:5672"

  vuejs:
    container_name: takeaway_vuejs
    build: ./vuejs
    volumes:
      - ./vuejs:/www
      - /www/node_modules

  nginx:
    container_name: takeaway_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - vuejs
